pskfyi/handy

cli/cmd.test.ts
Test for `cli/cmd` using "echo" failed in PowerShell:  
Added conditional logic to test based on OS.
=> test(cli/cmd): handle powershell

.github/workflows/pr-checks.yml, git/script/makeReleaseNotes.ts, md/script/evalCodeBlocks.ts
- Resolves the only issue that was preventing tests from passing
- Enables the test step in the workflow job for `macos-latest` only
=> Fix & enable tests for MacOS in CI

cli/cmd.stub.ts, cli/cmd.test.ts, cli/cmd.ts, md/codeBlock/eval.test.ts, md/codeBlock/eval.ts
=> feat(cli/cmd): don't throw with `fullResult` option

git/commit/get.ts
=> docs(git): fix JSDoc for `commit.getSpan()`; add examples

fs/globImport.test.ts, os/mod.ts, os/newlines.test.ts, os/newlines.ts, os/utils.ts, readme.md
Tiny helpers inspired by the work done to test `globImport` on windows.
=> feat(os): init; add `newlines` utilities

git/script/makeReleaseNotes.ts
I discovered while wrapping up #49 that the CLI portion of this option was not wired up.
=> fix(makeReleaseNotes): wire `inclusive` CLI flag

md/script/evalCodeBlocks.ts, readme.md
=> feat(evalCodeBlocks): allow blocks to opt out with `no-eval`

cli/cmd.ts, collection/largest.ts, collection/smallest.ts, deno.json, fs/globImport.ts, git/commit/conventional.test.ts, git/commit/conventional.ts, git/script/makeReleaseNotes.ts, graph/DirectedGraph.ts, io/clipboard.ts, md/codeBlock/create.ts, md/codeBlock/eval.ts, md/codeBlock/fenced.ts, md/codeBlock/indented.ts, md/codeBlock/infoString.ts, md/script/evalCodeBlocks.ts, object/setNestedEntry.ts, path/globRoot.ts, string/dedent.ts, string/indent.ts, string/sequence.ts, ts/evaluate.ts
* (types): require explicit return types (98a780f)
Because Handy is a library rather than an application, explicit return types help us understand when we might accidentally break an existing API. I've gone back and forth on this, but [this video](https://www.youtube.com/watch?v=nwSe95uFN8E) from esteemed TypeScript wizard @mattpocock pushed me over the edge.
Unfortunately Deno's linter has very few linting rules and no per-rule configurations, so our only option is to enable this rule for all functions even ones in test files and functions that aren't exported. Hopefully in the future we'll be able to apply this only to exported functions.
* (DirectedGraph): add `Vertex`, `Vertices`, and `Edge` types (10dab15)
* (fs/globImport): codify `ImportLike`; refactor JSDocs (e836e4b)
=> refactor(types): require explicit return types

.github/workflows/pr-checks.yml, _deps/fmt.ts, md/codeBlock/fenced.test.ts, md/codeBlock/regex.ts, md/script/evalCodeBlocks.ts, path/utils.ts, readme.md
=> ci: `test-readme` enhancements

_constants.ts, _test/constants.ts, fs/findNearestFile.test.ts, fs/glob.test.ts, fs/globImport.test.ts
I realized that the constants file is only for tests and so should be moved into the `_test` directory to signify that and to declutter the repo root.
This PR led to many insights which I spun off into #54, #55. Now that they've merged, this PR is appropriately small and focused 👏
=> refactor(constants): move `_constants.ts` -> `_test/constants.ts`

graph/DirectedGraph.test.ts, graph/DirectedGraph.ts, readme.md
* (DirectedGraph): add JSDoc examples (8c29fa1)
* (DirectedGraph): `.has()` accepts edges, paths, and is variadic (b69c485)
* (DirectedGraph): `.add()` accepts edges, paths, and is variadic (df6f6b1)
* (DirectedGraph): `.remove()` accepts edges, paths, and is variadic (f54d7c1)
* (DirectedGraph): namespace typedefs (cdbe1ed)
* **Breaking Change** (DirectedGraph): constrain and document vertex types (e589d41)
Previously vertices were `NonNullable` but this still allowed problematic `boolean`, `unknown`, and Array types. This commit constrains vertices to `string`, `number`, `symbol`, and non-Array objects, preventing confusion and setting up for API improvements that rely on arrays to represent edges and paths.
* (DirectedGraph): remove duplicative #addVertex call (1ac07f4)
* …
=> `DirectedGraph` enhancements

readme.md
`1000` was down-tuned to `100` to make the `test-readme` task faster, but the comment wasn't updated to match.
=> docs: fix incorrect readme comment

cli/cmd.ts, md/codeBlock/fenced.ts, readme.md, ts/evaluate.ts, ts/types.ts
Extracted from #79.
- refactor(ts): `Intersect` -> `Pretty`; expand input types; add `& {}`; docs
This refactor brings this helper type in line with [the original inspiration](https://twitter.com/mattpocockuk/status/1622730173446557697). During #79 I encountered situations where the `& {}` was necessary to coax the compiler into untangling complex types. I also learned that the `Record`-based type constraint was unnecessary, and that this helper has uses beyond just handling intersections, so I opted to fully implement the original helper except with a shorter name. I also took this opportunity to add a readme entry.
=> refactor(ts): `Intersect` -> `Pretty`

array/mod.ts, array/types.ts, readme.md
Extracted from #79.
- feat(array/types): init
- `Fill` replaces array values with a given value.
- `Flat` is analogous to `Array.prototype.flat()`
- `Indices` extracts the index values of an array.
- `Index` extracts a union of indices from an array.
- `FromIndices` describes a new array from a given array and a tuple of indices.
- `Reverse` describes an array with the same elements in reverse order.
- `Zip` combines two arrays into an array of tuples. Useful for creating object entries.
- The `Tuple` namespace clusters all helper types which respect tuples, which currently includes all types. This was a preferable alternative to starting a new top-level `tuple` module just to house these typedefs.
=> feat(array/types): init

cli/consoleSize.ts, cli/utils.ts, git/script/makeReleaseNotes.ts, md/script/evalCodeBlocks.ts, readme.md
See #93 
- feat(cli): add console size helpers
- `consoleWidth()` returns the actual console width in columns, else a fallback value when unable.
- `consoleHeight()` does the same for height in rows.
- `consoleSize()` does both at once.
=> feat(cli): add console size helpers

object/mod.ts, object/types.ts, readme.md
Extracted from #79.
- feat(object/types): init
- `Key` is a valid object key.
- `Entry` is a key-value tuple.
- `Pair` is a key-value pair in an object.
- `EntryToPair` converts an `Entry` to a `Pair`
- `FromEntries` converts `Entry`s to an object
- `ToEntries` converts an object to an array of `Entry`s
- The `Obj` namespace clusters these helper types.
=> feat(object/types): init

array/types.ts, collection/mod.ts, collection/types.ts, number/mod.ts, number/types.ts, readme.md, string/mod.ts, string/types.ts, ts/types.ts
Extracted from #97.
I recommend reading this one commit at a time.
It's all typedefs - no functions, so no unit tests.
=> Utility Types for `array`, `string`, `number`, `ts`, and `collection`

git/script/makeReleaseNotes.ts, md/script/evalCodeBlocks.ts, readme.md, string/elide.test.ts, string/elide.ts, string/utils.ts
See #94
- feat(string): add `elide` helpers
- `elideStart()` replaces the start of a string with ellipses
- `elideEnd()` replaces the end of a string with ellipses
- `elideMiddle()` replaces the middle of a string with ellipses
- `elideAround()` dynamically elides the start and/or end of a string with ellipses, centered around a chosen index
=> Add `elide` helpers

mermaid/_frontmatter.ts, mermaid/flowchart.test.ts, mermaid/flowchart.ts, mermaid/mod.ts, mermaid/utils.ts, readme.md
Closes #72 
Thanks for the guidance coding this together in our Liveshare.
=> Mermaid: DirectedGraph to basic flowchart

md/script/evalCodeBlocks.ts
Switches ✔️ for ✓, which hopefully resolves the issues with the former having non-dependable widths across environments.
In my dev machine's font in VS Code, these look almost indistinguishable, leading to my prior implementation.
=> fix(evalCodeBlocks): avoid check emoji

array/types.ts
Turns out the current implementation only handles tuples. `T extends [infer Head, infer ...Tail]` only pattern-matches against strings and tuples, where the 0th element can be inferred from the rest. Separate handling is required for non-tuple arrays, which this PR provides alongside examples.
- [Before Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAYgNgQ2AHgCpQgD2BAdgEwGcoAnCBfAe1zhCgFdcBrXSgd1wG0BdAPigC8UdFhwFCAKCilyVGnU4BLXADMIJKAAlZAGigA6Q8rUbUCRXG5SoAfi2yM2PEQbNWHHraidD+7RT1feCQ0czheK2kALm9-fEDDYJQzCwjrGJ4AbgkJUEhhejA4aCEk5E4AIgBBCr1KgCEK7j4oAHpWqDZKEiZJPOgqkg1SxBRcegBbACN1Hn42juN1MnwoBGIeXPABoYAmABFBWFHkcenZ7jnpdqgloYhV9e8rfqgAWUVMI7LKmrqKxp6CoAYSaPBaC063V6EiAA)
- [After Playground](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcBiAbAhjAPAFTlBmADsATAZzi …
=> feat(array/types): `Flat` respects non-tuple arrays

string/TextCursor.test.ts, string/TextCursor.ts
During parser work for indented code blocks, the inability to see spaces was a significant hindrance.
I also found that the signature for the Deno.customInspect function was incorrectly wired.
=> feat(string/TextCursor): visualize spaces as `·`

md/codeBlock/fenced.test.ts, md/codeBlock/fenced.ts, md/codeBlock/indented.test.ts, md/codeBlock/indented.ts, md/codeBlock/parse.test.ts
- Turns out that indented blocks are supposed to be exactly 4-space indented, and additional spaces are part of the content. Therefore `IndentedCodeBlockDetails["indentation"]` should be `"    "` every time and so is meaningless once the implementation is corrected.
- `FencedCodeBlockDetails["char"]` was originally provided as output from `fenced.parse()` in the hopes that the `parse` and `create` functions could accept each other's outputs as inputs, but that didn't happen. Now it's just chaff that's trivially derivable from `FencedCodeBlockDetails["fence"]`
=> refactor(md/codeBlock): remove unnecessary `Details` properties

js/evaluate.test.ts, js/evaluate.ts, js/mod.ts, js/utils.ts, md/codeBlock/eval.test.ts, md/codeBlock/eval.ts, readme.md
=> Evaluate JS
